---
- name: Let's copy our executable script to remote location, execute script and get result back.
  hosts: next-ansible-demo
  tasks:
     - name: Copy the script
       win_copy:
         src: /home/nutanix/hari/expand_disk.ps1
         dest: C:\Temp\expand_disk.ps1
 
     - name: Run the script
       win_shell: C:\temp\expand_disk.ps1
