---
- name: Let's copy our executable script to remote location, execute script and get result back.
  hosts: "{{ vm_ip }}"
  tasks:
     - name: Copy the script
       win_copy:
         content: |
           Resize-Partition -DriveLetter D -Size 14GB  
           
           Invoke-Sqlcmd -InputFile "C:\Users\Administrator\Desktop\change_db_size.sql" -ServerInstance "localhost"
         dest: C:\temp\expand_disk.ps1
 
     - name: Run the script
       win_shell: C:\temp\expand_disk.ps1
